spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/chat_db
    username: postgres
    password : postgres
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    enabled: false

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:9090/realms/chatapp
  servlet:
    multipart:
      max-file-size: 50MB

springdoc:
  default-produces-media-type: application/json

application:
  file:
    uploads:
      media-output-path: ./uploads

server:
  port: 8080