version: "3.8"
services:
  postgresql:
    container_name: postgrea_chat
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: /data/postgres
      POSTGRES_DB: chat_db
    volumes:
      - postgres:/data/postgres
    ports:
      - "5433:5432"
    networks:
      - chat-net
    restart: unless-stopped

  keycloak:
    container_name: keycloak_ms
    image: quay.io/keycloak/keycloak:26.3.1
    environment:
      - KC_BOOTSTRAP_ADMIN_USERNAME=admin
      - KC_BOOTSTRAP_ADMIN_PASSWORD=admin
    ports:
      - "9090:8080"
    networks:
      - chat-net
    restart: unless-stopped
    command: start-dev

networks:
  chat-net:
    driver: bridge

volumes:
  postgres: